# Generated by Django 5.1 on 2024-12-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyProfile',
        ),
    ]
